name: Generate Wrapper & Build APK (No Local PC)

permissions:
  contents: write

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Checkout OneUI lib only
        uses: actions/checkout@v5
        with:
          repository: OneUIProject/oneui-design
          path: oneui-temp
          sparse-checkout: |
            lib
          sparse-checkout-cone-mode: false

      - name: Move lib to project
        run: |
          rm -rf oneui-lib
          mv oneui-temp/lib oneui-lib
          rm -rf oneui-temp
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add oneui-lib
          git commit -m "Import/Update oneui-lib" || echo "no changes"
          git push || true

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Use project-local Gradle cache
        run: echo "GRADLE_USER_HOME=$GITHUB_WORKSPACE/.gradle" >> $GITHUB_ENV

      - name: Clear possibly corrupt Gradle cache
        run: rm -rf ~/.gradle/caches/jars-9 || true

      - name: Download Gradle 8.14.3 temporarily
        run: wget https://services.gradle.org/distributions/gradle-8.14.3-bin.zip -O gradle-8.14.3-bin.zip

      - name: Unzip temporary Gradle
        run: unzip -q gradle-8.14.3-bin.zip

      - name: Generate Gradle Wrapper
        run: ./gradle-8.14.3/bin/gradle wrapper --gradle-version 8.14.3 --distribution-type all

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Apply Spotless (auto-fix all formatters)
        run: ./gradlew spotlessApply

      - name: Show Spotless Report
        run: ./gradlew spotlessCheck || true

      - name: Build APK with Gradle Wrapper
        env:
          JITPACK_TOKEN: ${{ secrets.JITPACK_TOKEN }}
        run: ./gradlew assembleDebug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: oneui-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
